/**
 * Project store — holds the in-memory state of the currently open project.
 *
 * Files are generated by JiuwenSwarm agents and applied here as deltas.
 * The store is reset when the user navigates to a different project.
 */
import { create } from "zustand";
import type { FileDelta } from "../lib/streamParser";

export interface GenerationState {
  /** Whether an agent generation is currently in progress. */
  isGenerating: boolean;
  /** Name of the agent currently active (from status stream events). */
  activeAgent: string | null;
  /** Accumulated token text for the in-progress response. */
  streamBuffer: string;
}

interface ProjectState {
  /** Generated source files, keyed by relative path. */
  files: Record<string, string>;
  /** Currently active file in the editor/file-tree. */
  activeFile: string | null;
  /** Generation progress. */
  generation: GenerationState;
  /** Ordered list of rewindable message IDs (most recent last). */
  rewindStack: string[];

  // Actions
  applyDeltas: (deltas: FileDelta[]) => void;
  setActiveFile: (path: string | null) => void;
  setGenerating: (generating: boolean, agent?: string) => void;
  appendToken: (token: string) => void;
  clearStreamBuffer: () => void;
  pushRewindable: (messageId: string) => void;
  popRewindSnapshot: (messageId: string) => void;
  resetProject: () => void;
}

const INITIAL_GENERATION: GenerationState = {
  isGenerating: false,
  activeAgent: null,
  streamBuffer: "",
};

export const useProjectStore = create<ProjectState>()((set) => ({
  files: {},
  activeFile: null,
  generation: INITIAL_GENERATION,
  rewindStack: [],

  applyDeltas: (deltas) =>
    set((s) => {
      const next = { ...s.files };
      for (const delta of deltas) {
        if (delta.action === "delete") {
          delete next[delta.path];
        } else {
          next[delta.path] = delta.content;
        }
      }
      // Auto-select a sensible active file on first generation.
      const firstFile =
        deltas.find((d) => d.action !== "delete")?.path ?? null;
      return {
        files: next,
        activeFile: s.activeFile ?? firstFile,
      };
    }),

  setActiveFile: (path) => set({ activeFile: path }),

  setGenerating: (isGenerating, agent?: string) =>
    set((s) => ({
      generation: { ...s.generation, isGenerating, activeAgent: agent ?? null },
    })),

  appendToken: (token) =>
    set((s) => ({
      generation: {
        ...s.generation,
        streamBuffer: s.generation.streamBuffer + token,
      },
    })),

  clearStreamBuffer: () =>
    set((s) => ({
      generation: { ...s.generation, streamBuffer: "" },
    })),

  pushRewindable: (messageId) =>
    set((s) => ({
      rewindStack: [...s.rewindStack, messageId],
    })),

  popRewindSnapshot: (messageId) =>
    set((s) => {
      const idx = s.rewindStack.lastIndexOf(messageId);
      if (idx === -1) return s;
      return { rewindStack: s.rewindStack.slice(0, idx) };
    }),

  resetProject: () =>
    set({
      files: {},
      activeFile: null,
      generation: INITIAL_GENERATION,
      rewindStack: [],
    }),
}));
