/**
 * Project store — holds the in-memory state of the currently open project.
 *
 * Files are generated by JiuwenSwarm agents and applied here as deltas.
 * The store is reset when the user navigates to a different project.
 */
import { create } from "zustand";
import type { FileDelta } from "../lib/streamParser";

// ---------------------------------------------------------------------------
// Chat message types (shared with ChatPanel and MessageBubble)
// ---------------------------------------------------------------------------

export type MessageRole = "user" | "assistant" | "status";

export interface ChatMessage {
  id: string;
  role: MessageRole;
  content: string;
  isStreaming?: boolean;
  /** When set, renders an interactive "agent needs clarification" card. */
  question?: { requestId: string; text: string };
}

// ---------------------------------------------------------------------------
// Agent log entry (used by the Swarm panel)
// ---------------------------------------------------------------------------

/** What a log entry represents, so the Swarm panel can style it differently. */
export type AgentLogKind = "reasoning" | "status" | "tool";

export interface AgentLogEntry {
  status: string;
  time: number; // Date.now()
  /** Agent display name (e.g. "Architect") when known from the server. */
  agent?: string;
  /** Optional classifier; falls back to a heuristic in the panel. */
  kind?: AgentLogKind;
}

// ---------------------------------------------------------------------------
// Generation / rewind types
// ---------------------------------------------------------------------------

export interface GenerationState {
  isGenerating: boolean;
  activeAgent: string | null;
  streamBuffer: string;
}

export interface RewindEntry {
  msgId: string;
  snapshot: Record<string, string>;
}

// ---------------------------------------------------------------------------
// Store interface
// ---------------------------------------------------------------------------

interface ProjectState {
  // Files
  files: Record<string, string>;
  activeFile: string | null;

  // Chat history (owned here so Studio can export it)
  messages: ChatMessage[];

  // Generation progress
  generation: GenerationState;

  // Swarm activity log
  agentLog: AgentLogEntry[];

  // Rewind stack
  rewindStack: RewindEntry[];
  _pendingSnapshot: Record<string, string> | null;

  // Optional prompt injected by the template picker; cleared after first send
  initialPrompt: string | null;

  // --- File actions ---
  applyDeltas: (deltas: FileDelta[]) => void;
  setActiveFile: (path: string | null) => void;
  loadFiles: (files: Record<string, string>) => void;

  // --- Chat actions ---
  addChatMessage: (msg: ChatMessage) => void;
  updateLastAssistantMessage: (updater: (m: ChatMessage) => ChatMessage) => void;
  clearChatMessages: () => void;

  // --- Generation state ---
  setGenerating: (generating: boolean, agent?: string) => void;
  appendToken: (token: string) => void;
  clearStreamBuffer: () => void;

  // --- Swarm log ---
  appendAgentLog: (entry: AgentLogEntry) => void;
  appendAgentStatus: (status: string) => void;
  clearAgentLog: () => void;

  // --- Rewind ---
  snapshotForRewind: () => void;
  pushRewindable: (messageId: string) => void;
  popRewindSnapshot: () => Record<string, string> | null;
  restoreSnapshot: (snapshot: Record<string, string>) => void;

  // --- Template ---
  setInitialPrompt: (prompt: string | null) => void;

  resetProject: () => void;
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const INITIAL_GENERATION: GenerationState = {
  isGenerating: false,
  activeAgent: null,
  streamBuffer: "",
};

// ---------------------------------------------------------------------------
// Store
// ---------------------------------------------------------------------------

export const useProjectStore = create<ProjectState>()((set, get) => ({
  files: {},
  activeFile: null,
  messages: [],
  generation: INITIAL_GENERATION,
  agentLog: [],
  rewindStack: [],
  _pendingSnapshot: null,
  initialPrompt: null,

  // --- Files ---

  applyDeltas: (deltas) =>
    set((s) => {
      const next = { ...s.files };
      for (const delta of deltas) {
        if (delta.action === "delete") {
          delete next[delta.path];
        } else {
          next[delta.path] = delta.content;
        }
      }
      const firstFile = deltas.find((d) => d.action !== "delete")?.path ?? null;
      return { files: next, activeFile: s.activeFile ?? firstFile };
    }),

  setActiveFile: (path) => set({ activeFile: path }),

  loadFiles: (files) =>
    set((s) => ({
      files,
      activeFile: s.activeFile ?? Object.keys(files)[0] ?? null,
    })),

  // --- Chat ---

  addChatMessage: (msg) =>
    set((s) => ({ messages: [...s.messages, msg] })),

  updateLastAssistantMessage: (updater) =>
    set((s) => {
      const idx = [...s.messages].reverse().findIndex((m) => m.role === "assistant");
      if (idx === -1) return s;
      const realIdx = s.messages.length - 1 - idx;
      const next = [...s.messages];
      next[realIdx] = updater(next[realIdx]);
      return { messages: next };
    }),

  clearChatMessages: () => set({ messages: [] }),

  // --- Generation state ---

  setGenerating: (isGenerating, agent?: string) =>
    set((s) => ({
      generation: { ...s.generation, isGenerating, activeAgent: agent ?? null },
    })),

  appendToken: (token) =>
    set((s) => ({
      generation: { ...s.generation, streamBuffer: s.generation.streamBuffer + token },
    })),

  clearStreamBuffer: () =>
    set((s) => ({ generation: { ...s.generation, streamBuffer: "" } })),

  // --- Swarm log ---

  appendAgentLog: (entry) =>
    set((s) => {
      const next = [...s.agentLog, entry];
      // Keep log bounded at 200 entries.
      return { agentLog: next.length > 200 ? next.slice(-200) : next };
    }),

  appendAgentStatus: (status) =>
    get().appendAgentLog({ status, time: Date.now() }),

  clearAgentLog: () => set({ agentLog: [] }),

  // --- Rewind ---

  snapshotForRewind: () =>
    set((s) => ({ _pendingSnapshot: { ...s.files } })),

  pushRewindable: (messageId) =>
    set((s) => {
      const snapshot = s._pendingSnapshot ?? {};
      return {
        rewindStack: [...s.rewindStack, { msgId: messageId, snapshot }],
        _pendingSnapshot: null,
      };
    }),

  popRewindSnapshot: () => {
    const stack = get().rewindStack;
    if (stack.length === 0) return null;
    const entry = stack[stack.length - 1];
    set((s) => ({ rewindStack: s.rewindStack.slice(0, -1) }));
    return entry.snapshot;
  },

  restoreSnapshot: (snapshot) =>
    set({ files: snapshot, activeFile: Object.keys(snapshot)[0] ?? null }),

  // --- Template ---

  setInitialPrompt: (prompt) => set({ initialPrompt: prompt }),

  // --- Reset ---

  resetProject: () =>
    set({
      files: {},
      activeFile: null,
      messages: [],
      generation: INITIAL_GENERATION,
      agentLog: [],
      rewindStack: [],
      _pendingSnapshot: null,
      initialPrompt: null,
    }),
}));
