/**
 * Project store — holds the in-memory state of the currently open project.
 *
 * Files are generated by JiuwenSwarm agents and applied here as deltas.
 * The store is reset when the user navigates to a different project.
 */
import { create } from "zustand";
import type { FileDelta } from "../lib/streamParser";

export interface GenerationState {
  isGenerating: boolean;
  activeAgent: string | null;
  streamBuffer: string;
}

export interface RewindEntry {
  /** JiuwenSwarm message ID that marks this rewind point. */
  msgId: string;
  /** Snapshot of the file map BEFORE this generation ran. */
  snapshot: Record<string, string>;
}

interface ProjectState {
  files: Record<string, string>;
  activeFile: string | null;
  generation: GenerationState;
  /** Ordered list of rewind entries (most recent last). */
  rewindStack: RewindEntry[];
  /** Pre-generation file snapshot captured just before a submit. */
  _pendingSnapshot: Record<string, string> | null;

  // File actions
  applyDeltas: (deltas: FileDelta[]) => void;
  setActiveFile: (path: string | null) => void;
  /** Load a full file map (e.g. restored from persisted session). */
  loadFiles: (files: Record<string, string>) => void;

  // Generation state
  setGenerating: (generating: boolean, agent?: string) => void;
  appendToken: (token: string) => void;
  clearStreamBuffer: () => void;

  // Rewind
  /** Snapshot current files as the pre-generation baseline. Call before each submit. */
  snapshotForRewind: () => void;
  /** Associate the pending snapshot with a server-assigned message ID. */
  pushRewindable: (messageId: string) => void;
  /** Pop the latest entry, return its snapshot (or null if stack is empty). */
  popRewindSnapshot: () => Record<string, string> | null;
  /** Replace current files with a previously saved snapshot. */
  restoreSnapshot: (snapshot: Record<string, string>) => void;

  resetProject: () => void;
}

const INITIAL_GENERATION: GenerationState = {
  isGenerating: false,
  activeAgent: null,
  streamBuffer: "",
};

export const useProjectStore = create<ProjectState>()((set, get) => ({
  files: {},
  activeFile: null,
  generation: INITIAL_GENERATION,
  rewindStack: [],
  _pendingSnapshot: null,

  applyDeltas: (deltas) =>
    set((s) => {
      const next = { ...s.files };
      for (const delta of deltas) {
        if (delta.action === "delete") {
          delete next[delta.path];
        } else {
          next[delta.path] = delta.content;
        }
      }
      const firstFile = deltas.find((d) => d.action !== "delete")?.path ?? null;
      return {
        files: next,
        activeFile: s.activeFile ?? firstFile,
      };
    }),

  setActiveFile: (path) => set({ activeFile: path }),

  loadFiles: (files) =>
    set((s) => ({
      files,
      activeFile: s.activeFile ?? Object.keys(files)[0] ?? null,
    })),

  setGenerating: (isGenerating, agent?: string) =>
    set((s) => ({
      generation: { ...s.generation, isGenerating, activeAgent: agent ?? null },
    })),

  appendToken: (token) =>
    set((s) => ({
      generation: {
        ...s.generation,
        streamBuffer: s.generation.streamBuffer + token,
      },
    })),

  clearStreamBuffer: () =>
    set((s) => ({ generation: { ...s.generation, streamBuffer: "" } })),

  snapshotForRewind: () =>
    set((s) => ({ _pendingSnapshot: { ...s.files } })),

  pushRewindable: (messageId) =>
    set((s) => {
      const snapshot = s._pendingSnapshot ?? {};
      return {
        rewindStack: [...s.rewindStack, { msgId: messageId, snapshot }],
        _pendingSnapshot: null,
      };
    }),

  popRewindSnapshot: () => {
    const stack = get().rewindStack;
    if (stack.length === 0) return null;
    const entry = stack[stack.length - 1];
    set((s) => ({ rewindStack: s.rewindStack.slice(0, -1) }));
    return entry.snapshot;
  },

  restoreSnapshot: (snapshot) =>
    set({
      files: snapshot,
      activeFile: Object.keys(snapshot)[0] ?? null,
    }),

  resetProject: () =>
    set({
      files: {},
      activeFile: null,
      generation: INITIAL_GENERATION,
      rewindStack: [],
      _pendingSnapshot: null,
    }),
}));
